In [1465]:
import pandas as pd
import seaborn as sns
import sklearn

# Read & Merge Dataframes

In [1466]:
paths=[
       ##! data scientist jobs
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/data_scientist_jobs_us.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/data_scientist_jobs_uk.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/data_scientist_jobs_canada.csv",
        "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/data_scientist_jobs_indianapolis.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/data_scientist_jobs_singapore.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/data_scientist_jobs_australia.csv",
       ##! data analyst jobs
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/data_analyst_jobs_us.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/data_analyst_jobs_uk.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/data_analyst_jobs_canada.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/data_analyst_jobs_indianapolis.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/data_analyst_jobs_singapore.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/data_analyst_jobs_australia.csv",
       ##! ai engineer jobs
        "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/ai_engineer_jobs_united_states.csv",
        "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/ai_engineer_jobs_united_kingdom.csv",
        "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/ai_engineer_jobs_indianapolis.csv",
        ##! ml engineer jobs
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/ml_engineer_jobs_us.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/ml_engineer_jobs_uk.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/ml_engineer_jobs_indianapolis.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/ml_engineer_jobs_singapore.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/ml_engineer_jobs_australia.csv",
       ##! deep learning engineer jobs
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/deep_learning_engineer_jobs_us.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/deep_learning_engineer_jobs_uk.csv",
       ]
dfs = [pd.read_csv(path) for path in paths]
merged_df = pd.concat(dfs, ignore_index=True)

In [1467]:
##! save the merged dataframe to a new csv file
import os

os.makedirs("/home/salah-mohammed/Data_Science/ds_jobs_project/data/merged_data_frames", exist_ok=True)
merged_df.to_csv("/home/salah-mohammed/Data_Science/ds_jobs_project/data/merged_data_frames/merged_jobs_data.csv", index=False)

In [1468]:
## add the old glassdoor data (big but old from 2020)
paths=[
       ##! data scientist jobs
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/data_scientist_jobs_us.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/data_scientist_jobs_uk.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/data_scientist_jobs_canada.csv",
        "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/data_scientist_jobs_indianapolis.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/data_scientist_jobs_singapore.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/data_scientist_jobs_australia.csv",
       ##! data analyst jobs
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/data_analyst_jobs_us.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/data_analyst_jobs_uk.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/data_analyst_jobs_canada.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/data_analyst_jobs_indianapolis.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/data_analyst_jobs_singapore.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/data_analyst_jobs_australia.csv",
       ##! ai engineer jobs
        "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/ai_engineer_jobs_united_states.csv",
        "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/ai_engineer_jobs_united_kingdom.csv",
        "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/ai_engineer_jobs_indianapolis.csv",
        ##! ml engineer jobs
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/ml_engineer_jobs_us.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/ml_engineer_jobs_uk.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/ml_engineer_jobs_indianapolis.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/ml_engineer_jobs_singapore.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/ml_engineer_jobs_australia.csv",
       ##! deep learning engineer jobs
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/deep_learning_engineer_jobs_us.csv",
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/deep_learning_engineer_jobs_uk.csv",
       
       ##! old glassdoor data
       "/home/salah-mohammed/Data_Science/ds_jobs_project/data/data_frames/old_glassdoor_jobs.csv"
       ]
all_dfs = [pd.read_csv(path) for path in paths]
big_merged_df = pd.concat(all_dfs, ignore_index=True)

In [1469]:
##! save the big merged dataframe to a new csv file
import os

os.makedirs("/home/salah-mohammed/Data_Science/ds_jobs_project/data/merged_data_frames", exist_ok=True)
big_merged_df.to_csv("/home/salah-mohammed/Data_Science/ds_jobs_project/data/merged_data_frames/big_merged_jobs_data.csv", index=False)

# Business Understanding
1. define the problem
- The job market for data-related roles (DS, ML, AI, DA) is large and hard to navigate. Job seekers don't know which skills are most in-demand, which locations pay the most, or how salaries vary across roles and experience levels. This project analyzes Glassdoor job listings to surface those patterns.
2. who are the stakholders
- Job seekers (primary) — people transitioning into or growing within data roles
- Hiring managers — understand what the market looks like for competitors
- Bootcamps/educators — know which skills to teach
- For me: demonstrate end-to-end DS capability
3. what do they need
- Which skills appear most in job descriptions
- Salary ranges by role, location, seniority, and company size
- Which industries hire the most data roles
- Countries market differences
- Entry-level vs senior role distribution
4. what is success
- A clean dataset ready for analysis after cleaning
- At least 3 actionable insights a job seeker can use
- A dashboard or report showing salary trends, top skills, top hiring companies
- A model that predicts estimated salary from job features (stretch goal)
5. what data exsists
- Scrapped CSVs (DS, ML Engineer, AI Engineer, Deep Learning, Data Analyst)
- Job Title	Company	Location	Salary Estimate	Job Description	Job Age

# Data Understanding
1. load data: .head() => .info() => .describe().
2. check nulls,  duplicates.
3. EDA Univariate (distripution for each feature).
4. EDA Multivariate (feature vs target).

In [1470]:
df=merged_df.copy() ##? data frames for the merged data without the old glassdoor data (data from 2020)
big_df=big_merged_df.copy()##? with the old glassdoor data (data from 2020)

In [1471]:
df=pd.read_csv("/home/salah-mohammed/Data_Science/ds_jobs_project/data/merged_data_frames/merged_jobs_data.csv")
df.head(15)

,Job Title,Company,Location,Salary Estimate,Job Description,Job Age
0,Data Scientist,WINTrio,Remote,NaN,Takes research methodology and translates the ...,30d+
1,"Language Data Scientist, Alexa AI",Amazon,"Seattle, WA",$136K - $184K (Employer provided),3+ years of machine learning/statistical model...,18d
2,"Data Scientist, WWPS ProServe Data and Machine...",Amazon Web Services,"Jessup, MD",$136K - $184K (Employer provided),"Working closely with stakeholders, you'll asse...",30d+
3,"Data Scientist I, SHAKE",Amazon,"Seattle, WA",$108K - $160K (Employer provided),You will work on our Science team and partner ...,27d
4,Lead Data Scientist,State Farm,"Bloomington, IL",$107K - $142K (Employer provided),Completed master’s or other advanced degree in...,18d
5,Data Scientist,Deloitte,"Arlington, VA",$101K - $143K (Glassdoor est.),"Design, wireframe, and develop dashboards and ...",12d
6,AI and Machine Learning,Tata Consultancy Services,"Westfield, NJ",$100K - $150K (Employer provided),Mentoring and technical leadership capabilitie...,3d
7,Data Science Engineer,Tata Consultancy Services,"Durham, NC",$90K - $110K (Employer provided),Experience with prompt engineering and few-sho...,5d
8,Data Scientist,Tata Consultancy Services,"San Antonio, TX",$100K - $140K (Employer provided),Data Visualization and Reporting: Using tools ...,30d+
9,Data Scientist,Tata Consultancy Services,"Louisville, KY",$110K - $140K (Employer provided),"3+ years in decision analytics, data science, ...",27d
10,Lead Data Scientist,Humana,United States,$142K - $196K (Employer provided),Manage the execution of data science strategie...,30d+
11,Senior Data Scientist,Humana,United States,$118K - $162K (Employer provided),Associates who live and work from Home in the ...,30d+
12,Machine Learning - Data Scientist,Apple,"Boulder, CO",$132K - $245K (Employer provided),"Strong documentation skills, including the abi...",4d
13,"AIML - Sr Data Scientist, Evaluation",Apple,"Cupertino, CA",$181K - $318K (Employer provided),Advanced degree in a quantitative field such a...,4d
14,"AIML - Sr Data Scientist, Evaluation",Apple,"Seattle, WA",$172K - $302K (Employer provided),Work with evaluation/experimentation engineeri...,4d

In [1472]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 660 entries, 0 to 659
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Job Title        660 non-null    str
 1   Company          660 non-null    str
 2   Location         660 non-null    str
 3   Salary Estimate  570 non-null    str
 4   Job Description  660 non-null    str
 5   Job Age          660 non-null    str
dtypes: str(6)
memory usage: 239.3 KB

In [1473]:
df.describe() # since all cols for now are str or object

,Job Title,Company,Location,Salary Estimate,Job Description,Job Age
count,660,660,660,570,660,660
unique,435,390,169,465,603,29
top,Data Scientist,Deloitte,"Indianapolis, IN",$113K - $208K (Employer provided),Deploy and support AI tools for hardware engin...,30d+
freq,60,38,104,11,6,342

In [1474]:
df.duplicated().sum() # 28 duplicates, so drop
df=df.drop_duplicates()

In [1475]:
df.isna().sum()
# all nans are in salary estimate cols, so we will handle them later when we clean the salary cols

Job Title           0
Company             0
Location            0
Salary Estimate    88
Job Description     0
Job Age             0
dtype: int64

----------------------------------------
1. Salary estimate: there is different currencies.
-  $ (usa)
- FCFA, and £ (uk)
- A$ (austrailia)
- Ca$ (canada)
- SGD (singapore)
---------------------------------------------------------
- i will save each currency in seperate column (original currency)

## EDA Functions

In [1476]:
"""UNIVARIATE PLOTTING FUNCTIONS FOR EDA"""
# Add the print statements to the function
def explore_categorical(df, x, fillna = True, placeholder = 'MISSING',
                        figsize = (6,4), order = None):
  """Creates a seaborn countplot with the option to temporarily fill missing values
  Prints statements about null values, cardinality, and checks for
  constant/quasi-constant features.
  Source:{PASTE IN FINAL LESSON LINK}
  """
  # Make a copy of the dataframe and fillna
  temp_df = df.copy()
  # Before filling nulls, save null value counts and percent for printing
  null_count = temp_df[x].isna().sum()
  null_perc = null_count/len(temp_df)* 100
  # fillna with placeholder
  if fillna == True:
    temp_df[x] = temp_df[x].fillna(placeholder)
  # Create figure with desired figsize
  fig, ax = plt.subplots(figsize=figsize)
  # Plotting a count plot
  sns.countplot(data=temp_df, x=x, ax=ax, order=order)
  # Rotate Tick Labels for long names
  ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right')
  # Add a title with the feature name included
  ax.set_title(f"Column: {x}", fontweight='bold')

  # Fix layout and show plot (before print statements)
  fig.tight_layout()
  plt.show()
  print("*****"*10)
  # Print null value info
  print(f"- NaN's Found: {null_count} ({round(null_perc,2)}%)")
  # Print cardinality info
  nunique = temp_df[x].nunique()
  print(f"- Unique Values: {nunique}")
  # First find value counts of feature
  val_counts = temp_df[x].value_counts(dropna=False)
  # Define the most common value
  most_common_val = val_counts.index[0]
  # Define the frequency of the most common value
  freq = val_counts.values[0]
  # Calculate the percentage of the most common value
  perc_most_common = freq / len(temp_df) * 100
  # Print the results
  print(f"- Most common value: '{most_common_val}' occurs {freq} times ({round(perc_most_common,2)}%)")
  # print message if quasi-constant or constant (most common val more than 98% of data)
  if perc_most_common > 98:
    print(f"\n- [!] Warning: '{x}' is a constant or quasi-constant feature and should be dropped.")
  else:
    print("- Not constant or quasi-constant.")
  return fig, ax


# TO DO: add the new print statements from explore_categorical
def explore_numeric(df, x, figsize=(6,5) ):
  """Creates a seaborn histplot and boxplot with a share x-axis,
  Prints statements about null values, cardinality, and checks for
  constant/quasi-constant features.
  Source:{PASTE IN FINAL LESSON LINK}
  """

  ## Save null value counts and percent for printing
  null_count = df[x].isna().sum()
  null_perc = null_count/len(df)* 100


  ## Making our figure with gridspec for subplots
  gridspec = {'height_ratios':[0.7,0.3]}
  fig, axes = plt.subplots(nrows=2, figsize=figsize,
                           sharex=True, gridspec_kw=gridspec)
  # Histogram on Top
  sns.histplot(data=df, x=x, ax=axes[0])

  # Boxplot on Bottom
  sns.boxplot(data=df, x=x, ax=axes[1])

  ## Adding a title
  axes[0].set_title(f"Column: {x}", fontweight='bold')

  ## Adjusting subplots to best fill Figure
  fig.tight_layout()

  # Ensure plot is shown before message
  plt.show()

  print("*****"*10)
  # Print null value info
  print(f"- NaN's Found: {null_count} ({round(null_perc,2)}%)")
  # Print cardinality info
  nunique = df[x].nunique()
  print(f"- Unique Values: {nunique}")


  # Get the most most common value, its count as # and as %
  most_common_val_count = df[x].value_counts(dropna=False).head(1)
  most_common_val = most_common_val_count.index[0]
  freq = most_common_val_count.values[0]
  perc_most_common = freq / len(df) * 100

  print(f"- Most common value: '{most_common_val}' occurs {freq} times ({round(perc_most_common,2)}%)")

  # print message if quasi-constant or constant (most common val more than 98% of data)
  if perc_most_common > 98:
    print(f"\n- [!] Warning: '{x}' is a constant or quasi-constant feature and should be dropped.")
  else:
    print("- Not constant or quasi-constant.")
  return fig, axes

In [1477]:
"""MULTIVARIATE PLOTTING FUNCTIONS VS. NUMERIC TARGET"""

def plot_categorical_vs_target(df, x, y='rating',figsize=(6,4),
                            fillna = True, placeholder = 'MISSING',
                            order = None):
  """Plots a combination of a seaborn barplot of means combined with
  a seaborn stripplot to show the spread of the data.
  Source:{PASTE IN FINAL LESSON LINK}
  """
  # Make a copy of the dataframe and fillna
  temp_df = df.copy()
  # fillna with placeholder
  if fillna == True:
    temp_df[x] = temp_df[x].fillna(placeholder)

  # or drop nulls prevent unwanted 'nan' group in stripplot
  else:
    temp_df = temp_df.dropna(subset=[x])
  # Create the figure and subplots
  fig, ax = plt.subplots(figsize=figsize)

    # Barplot
  sns.barplot(data=temp_df, x=x, y=y, ax=ax, order=order, alpha=0.6,
              linewidth=1, edgecolor='black', errorbar=None)

  # Boxplot
  sns.stripplot(data=temp_df, x=x, y=y, hue=x, ax=ax,
                order=order, hue_order=order, legend=False,
                edgecolor='white', linewidth=0.5,
                size=3,zorder=0)
  # Rotate xlabels
  ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right')

  # Add a title
  ax.set_title(f"{x} vs. {y}", fontweight='bold')
  fig.tight_layout()
  return fig, ax


def plot_numeric_vs_target(df, x, y,
                           figsize=(6,4),
                           ):
  """Plots a seaborn regplot with Pearson's correlation (r) added
  to the title.
  Source:{PASTE IN FINAL LESSON LINK}
  """
  # Calculate the correlation
  corr = df[[x,y]].corr().round(2)
  r = corr.loc[x,y]

  # Plot the data
  fig, ax = plt.subplots(figsize=figsize)
  scatter_kws={'ec':'white','alpha':0.8}
  sns.regplot(data=df, x=x, y=y, ax=ax,scatter_kws=scatter_kws)

  ## Add the title with the correlation
  ax.set_title(f"{x} vs. {y} (r = {r})", fontweight='bold')

  # Make sure the plot is shown before the print statement
  plt.show()

  return fig, ax

# Data preperation: clean, engineer, split-no Leakage
1. Fix inconsistencies, drop true outliers with domain logic
2. Feature engineering (new features, encoding decisions)

In [1478]:
# idea came to my mind, what if in salary_TYPE column , there is hour and employer provided at the same time, or hour and glassdoor est. 
# so the best thing is to make 3 cols, one for glassdoor est. one for employer provided, and one for hourly or not.

def check_employer_provided(x):
    if pd.isna(x):
        return 0
    return int('employer provided' in x.lower())


def check_hourly(x):
    if pd.isna(x):
        return 0
    return int('hour' in x.lower())


def check_glassdoor_estimate(x):
    if pd.isna(x):
        return 0
    return int('glassdoor' in x.lower())

df['Hourly']=df['Salary Estimate'].apply(check_hourly)
df['Glassdoor_Estimate']=df['Salary Estimate'].apply(check_glassdoor_estimate)
df['Employer_Provided']=df['Salary Estimate'].apply(check_employer_provided)

# to remove the salary type from salary estimate col
df['Salary Estimate']=df['Salary Estimate'].str.split('(').str[0]
df['Salary Estimate']=df['Salary Estimate'].str.split('P').str[0]
df['Salary Estimate']=df['Salary Estimate'].str.replace('K','')

def extract_currency(x):
    if pd.isna(x):
        return 'Unknown'
    if 'CA$' in x:
        return 'CA$'
    if 'A$' in x:
        return 'A$'
    if '£' in x:
        return '£'
    if '$' in x:
        return '$'
    if 'FCFA' in x:
        return 'FCFA'
    if 'SGD' in x:
        return 'SGD'
    else:
        return 'Unknown'

df['currency']=df['Salary Estimate'].apply(extract_currency)

df.head(65)

,Job Title,Company,Location,Salary Estimate,Job Description,Job Age,Hourly,Glassdoor_Estimate,Employer_Provided,currency
0,Data Scientist,WINTrio,Remote,NaN,Takes research methodology and translates the ...,30d+,0,0,0,Unknown
1,"Language Data Scientist, Alexa AI",Amazon,"Seattle, WA",$136 - $184,3+ years of machine learning/statistical model...,18d,0,0,1,$
2,"Data Scientist, WWPS ProServe Data and Machine...",Amazon Web Services,"Jessup, MD",$136 - $184,"Working closely with stakeholders, you'll asse...",30d+,0,0,1,$
3,"Data Scientist I, SHAKE",Amazon,"Seattle, WA",$108 - $160,You will work on our Science team and partner ...,27d,0,0,1,$
4,Lead Data Scientist,State Farm,"Bloomington, IL",$107 - $142,Completed master’s or other advanced degree in...,18d,0,0,1,$
...,...,...,...,...,...,...,...,...,...,...
60,Data Scientist,CGI,Halifax,CA$65 - CA$125,. A completed college diploma or university de...,18d,0,0,1,CA$
61,data scientist,ONIKON Creative,Shediac,CA$42.00 - CA$45.00,Design methods of collecting and processing da...,10d,1,0,1,CA$
62,Data Scientist,Interac,Toronto,CA$90 - CA$120,Significant experience working with implementi...,30d+,0,0,1,CA$
63,Data Scientist,Koch,North Vancouver,CA$100 - CA$150,"Bachelor's or Master's degree in Statistics, M...",30d+,0,0,1,CA$
64,Data Scientist,BGIS,Markham,CA$82 - CA$103,Utilize your educational background in a quant...,4d,0,0,1,CA$

In [1479]:
##! non-professional way to split
##! split {$136K - $184K (Employer provided)} to two columns, column holding salary, and column holding the salary type (glassdoor est. or not) 
# this is to split (still didnt remove the salary type from salary estimate col)

#def split_salary_type(salary_estimate):
 #   if pd.isna(salary_estimate):
  #      return None
  #  # check if the salary type is hourly or not
  #  if 'hour' in salary_estimate.lower():
  #      return 'Hourly'
  # return salary_estimate.split('(')[1].strip().replace(')', '')
#df['salary_type']=df['Salary Estimate'].apply(split_salary_type)


# to remove the salary type from salary estimate col
#df['Salary Estimate']=df['Salary Estimate'].str.split('(').str[0]

#df.head(96)

In [1480]:
# i made 2 functions because some salary estimates have just one salary (like: CA$42.00 - CA$45.00 Per Hour (Employer provided)) and may don't have ('-') to split
def split_min_salary(salary_estimate):
    if pd.isna(salary_estimate):
        return None
    min_salary=salary_estimate.split('-')[0].strip()
    return min_salary

def split_max_salary(salary_estimate):
    if pd.isna(salary_estimate):
        return None
    if '-' not in salary_estimate:
        return split_min_salary(salary_estimate) # if there is no max salary, return the min salary as the max salary
    max_salary=salary_estimate.split('-')[1].strip()
    return max_salary

df['min_salary']=df['Salary Estimate'].apply(split_min_salary).str.replace({'$':'', '£':'', 'CA':'', 'SGD':'', 'FCFA':'', 'A$':'','Ca':''})
df['max_salary']=df['Salary Estimate'].apply(split_max_salary).str.replace({'$':'', '£':'', 'CA':'', 'SGD':'', 'FCFA':'', 'A$':'','Ca':''})

df.head(270)

,Job Title,Company,Location,Salary Estimate,Job Description,Job Age,Hourly,Glassdoor_Estimate,Employer_Provided,currency,min_salary,max_salary
0,Data Scientist,WINTrio,Remote,NaN,Takes research methodology and translates the ...,30d+,0,0,0,Unknown,NaN,NaN
1,"Language Data Scientist, Alexa AI",Amazon,"Seattle, WA",$136 - $184,3+ years of machine learning/statistical model...,18d,0,0,1,$,136,184
2,"Data Scientist, WWPS ProServe Data and Machine...",Amazon Web Services,"Jessup, MD",$136 - $184,"Working closely with stakeholders, you'll asse...",30d+,0,0,1,$,136,184
3,"Data Scientist I, SHAKE",Amazon,"Seattle, WA",$108 - $160,You will work on our Science team and partner ...,27d,0,0,1,$,108,160
4,Lead Data Scientist,State Farm,"Bloomington, IL",$107 - $142,Completed master’s or other advanced degree in...,18d,0,0,1,$,107,142
...,...,...,...,...,...,...,...,...,...,...,...,...
265,Service Analytics Data Analyst,Information Technology Senior Management Forum,Vancouver,CA$131 - CA$205,"Leverages recognized domain expertise, busines...",24d,0,0,1,CA$,131,205
266,Data Analyst,XBOW,Remote,NaN,Support the development teams in their use of ...,19d,0,0,0,Unknown,NaN,NaN
267,Data Analyst II,Intact,St. John's,CA$69 - CA$85,"Bachelor’s degree in data-related field (i.e.,...",24h,0,0,1,CA$,69,85
268,Data Analyst (Hybrid),Morgan Stanley,Montreal,CA$88 - CA$93,"Partnering with control owners, project manage...",30d+,0,1,0,CA$,88,93
269,Data Analyst,VersaBank,London,CA$45 - CA$74,Comprehensive benefits program and fitness pro...,8d,0,1,0,CA$,45,74

In [1481]:
df.info()

<class 'pandas.DataFrame'>
Index: 632 entries, 0 to 659
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Job Title           632 non-null    str
 1   Company             632 non-null    str
 2   Location            632 non-null    str
 3   Salary Estimate     544 non-null    object
 4   Job Description     632 non-null    str
 5   Job Age             632 non-null    str
 6   Hourly              632 non-null    int64
 7   Glassdoor_Estimate  632 non-null    int64
 8   Employer_Provided   632 non-null    int64
 9   currency            632 non-null    str
 10  min_salary          544 non-null    str
 11  max_salary          544 non-null    str
dtypes: int64(3), object(1), str(8)
memory usage: 250.5+ KB

In [1482]:
# A$ after we removed $, A still there, so we need to remove A as well from min_salary and max_salary cols
a111=df.loc[df['min_salary']=='A111']
df['min_salary']=df['min_salary'].str.replace({'A':''})

In [1483]:

df['max_salary']=df['max_salary'].str.replace({'A':'','M':''})

In [1484]:
test=df.loc[df['max_salary']=='2M']
test

Empty DataFrame
Columns: [Job Title, Company, Location, Salary Estimate, Job Description, Job Age, Hourly, Glassdoor_Estimate, Employer_Provided, currency, min_salary, max_salary]
Index: []

In [1485]:
df['min_salary']=df['min_salary'].astype('float')

df['max_salary']=df['max_salary'].astype('float')

In [1486]:
df.loc[df['max_salary']==df['min_salary']] # as i said previously, when salary estimate has just one salary, i put it in both min and max salary cols

,Job Title,Company,Location,Salary Estimate,Job Description,Job Age,Hourly,Glassdoor_Estimate,Employer_Provided,currency,min_salary,max_salary
30,Data Scientist,Mayden,"Bath, England",£45,Exposure to working with clients and customers...,30d+,0,0,1,£,45.00,45.00
43,Data Scientist,GCHQ,"Cheltenham, England",£38,"No matter what you do, you’ll always be genero...",7d,0,0,1,£,38.00,38.00
94,Data Scientist,Novisync,"Indianapolis, IN",$41.48,The Data Scientist Intermediate may have super...,24h,1,0,1,$,41.48,41.48
142,Data Scientist,Silent Eight,Singapore,SGD 120,We're building AI-native tools that harness th...,2d,0,1,0,SGD,120.00,120.00
166,Machine Learning Engineer / Data Scientist,The Argyle Network,Sydney,A$150,"Experience working with financial, registry, o...",30d+,0,0,1,A$,150.00,150.00
176,Senior Data Scientist,Ausgrid,Haymarket,A$190,"Bachelor’s degree in Computer Science, Softwar...",25d,0,0,1,A$,190.00,190.00
181,ICQA Data Analyst,Amazon,"Avenel, NJ",$25.00,Responsible for teaching leadership team how t...,11d,1,0,1,$,25.00,25.00
196,Business Analyst :: $35/hr. :: 7+ stakeholder ...,Software Technology,"Harrisburg, PA",$35.00,Experience working with users to develop and i...,5d,1,0,1,$,35.00,35.00
238,Data Analyst Apprentice,QA,"Newcastle upon Tyne, England",£25,Level 3 qualification (apprenticeship/A-levels...,18d,0,0,1,£,25.00,25.00
261,data analyst - informatics and systems,SnapPay,Mississauga,CA$43.96,Develop and implement data administration poli...,30d+,1,0,1,CA$,43.96,43.96
262,Sourcing Data Analyst,Ya Ya Foods,Toronto,CA$70,"Bachelor’s degree in Business, Commerce, Suppl...",15d,0,0,1,CA$,70.00,70.00
287,Finance Performance Analyst - Office of Educat...,City of Indianapolis,"Indianapolis, IN",$59,"Research federal, state, and local grant oppor...",12d,0,0,1,$,59.00,59.00
334,Analyst Data,The Perth Mint,Australia,A$110,Competitive salaries and employee discounts. T...,19d,0,0,1,A$,110.00,110.00
349,Data Analyst,EdgeRed Analytics,Sydney,A$90,A relevant tertiary qualification with at leas...,12d,0,0,1,A$,90.00,90.00
359,Senior Data Analyst,City of Greater Geelong,Geelong,A$122,"Support end-to-end data migration activities, ...",14d,0,0,1,A$,122.00,122.00
386,"Full Stack Engineer (AI)-Chicago, IL",AHU Technology,"Washington, DC",$58.00,Agentic & Workflow Engineering: Design and imp...,30d+,1,0,1,$,58.00,58.00
399,AI Engineer,Durlston Partners,"London, England",£150,"In this role, you will design, develop, and de...",30d+,0,0,1,£,150.00,150.00
407,AI Engineer (Catalyst),Fifth Dimension,"London, England",£200,Build and evolve our AI intelligence platform—...,20d,0,0,1,£,200.00,200.00
449,QA Validation Engineer,RADcube,"Indianapolis, IN",$80,Implement and maintain automated regression te...,6d,0,0,1,$,80.00,80.00
531,Consult-TC-AI and Data-E2E-Data-Enterp Data-DE...,EY,"Indianapolis, IN",$135,"Must have a Bachelor’s degree in Business, Eco...",20d,0,0,1,$,135.00,135.00
570,ML Software Engineer,Woolworths Group,Bella Vista,A$135,"Work collaboratively with Data Scientists, ML ...",30d+,0,1,0,A$,135.00,135.00
578,Machine Learning Engineer / Data Scientist,The Argyle Network,Sydney,A$150,Lead the ML journey – own end-to-end projects ...,30d+,0,0,1,A$,150.00,150.00
634,Senior Machine Learning Engineer,WLT Group,Remote,FCFA 80,Lead the design and implementation of scalable...,30d+,0,0,1,FCFA,80.00,80.00

In [1487]:
df.describe()

,Hourly,Glassdoor_Estimate,Employer_Provided,min_salary,max_salary
count,632.000000,632.000000,632.000000,544.000000,544.000000
mean,0.015823,0.424051,0.436709,92.669926,141.034210
std,0.124888,0.494589,0.496371,44.935404,78.491049
min,0.000000,0.000000,0.000000,3.000000,2.000000
25%,0.000000,0.000000,0.000000,63.000000,90.000000
50%,0.000000,0.000000,0.000000,85.500000,129.000000
75%,0.000000,1.000000,1.000000,116.500000,180.000000
max,1.000000,1.000000,1.000000,380.000000,630.000000

In [1488]:
df.loc[df['min_salary']<20]# I will consider that these aren't possible, so i will *12
df.loc[df['min_salary']<20, 'min_salary'] *= 12
df.loc[df['max_salary']<20]# index 88 , the scrapper did'nt fetch the salary estimate correctly, so i will change max to 200, also i will *12
df.loc[88, 'max_salary'] = 200
df.loc[df['max_salary']<20, 'max_salary'] *= 12

In [1489]:
df.loc[df['max_salary']>=400] # they are absolutly possible (630k), since the company is antrhopic (calude)

,Job Title,Company,Location,Salary Estimate,Job Description,Job Age,Hourly,Glassdoor_Estimate,Employer_Provided,currency,min_salary,max_salary
114,AI & GenAI Data Scientist - EUR- Director,PwC,"Indianapolis, IN",$155 - $410,"At PwC, our people in data and analytics engin...",14d,0,0,1,$,155.0,410.0
130,Data Scientist,Tribus It,Singapore,SGD 200 - SGD 500,"Design data quality frameworks, alerts and rep...",12d,0,0,1,SGD,200.0,500.0
395,AI Research Engineer,Normal Computing,"London, England",£300 - £400,You’ll write production‑quality research code ...,30d+,0,0,1,£,300.0,400.0
471,"Research Engineer, Privacy",OpenAI,"San Francisco, CA",$380 - $445,"We build essential production services, develo...",30d+,0,0,1,$,380.0,445.0
631,"Research Engineer, Machine Learning (Reinforce...",Anthropic,"London, England",£260 - £630,"For sales roles, the range provided is the rol...",30d+,0,0,1,£,260.0,630.0
638,"Research Engineer, Pretraining",Anthropic,"London, England",£260 - £630,"For sales roles, the range provided is the rol...",30d+,0,0,1,£,260.0,630.0

In [1490]:
df.describe()

,Hourly,Glassdoor_Estimate,Employer_Provided,min_salary,max_salary
count,632.000000,632.000000,632.000000,544.000000,544.000000
mean,0.015823,0.424051,0.436709,93.316985,142.267665
std,0.124888,0.494589,0.496371,44.250898,77.436056
min,0.000000,0.000000,0.000000,20.000000,23.000000
25%,0.000000,0.000000,0.000000,63.000000,91.000000
50%,0.000000,0.000000,0.000000,86.500000,130.000000
75%,0.000000,1.000000,1.000000,116.500000,180.000000
max,1.000000,1.000000,1.000000,380.000000,630.000000

In [1491]:
df['avg_salary']=(df['min_salary']+df['max_salary'])/2

In [1492]:
#df['job_age_days'] = df['Job Age'].str.replace('d+', '', regex=False)\
 #                                 .str.replace('d', '', regex=False)\
 #                                 .str.replace('h', '', regex=False)\
  #                                .astype(float)

In [1493]:
# handle hourly salaries, since it wont be comparable to annual salaries.
# we will convert them to annual salaries by multiplying them by 2080 (40 hours per week * 52 weeks per year)
df.loc[df['Hourly']==1,['min_salary','max_salary','avg_salary']]*= 2080/1000

In [1494]:
df.head(96)

,Job Title,Company,Location,Salary Estimate,Job Description,Job Age,Hourly,Glassdoor_Estimate,Employer_Provided,currency,min_salary,max_salary,avg_salary
0,Data Scientist,WINTrio,Remote,NaN,Takes research methodology and translates the ...,30d+,0,0,0,Unknown,NaN,NaN,NaN
1,"Language Data Scientist, Alexa AI",Amazon,"Seattle, WA",$136 - $184,3+ years of machine learning/statistical model...,18d,0,0,1,$,136.0000,184.0000,160.0000
2,"Data Scientist, WWPS ProServe Data and Machine...",Amazon Web Services,"Jessup, MD",$136 - $184,"Working closely with stakeholders, you'll asse...",30d+,0,0,1,$,136.0000,184.0000,160.0000
3,"Data Scientist I, SHAKE",Amazon,"Seattle, WA",$108 - $160,You will work on our Science team and partner ...,27d,0,0,1,$,108.0000,160.0000,134.0000
4,Lead Data Scientist,State Farm,"Bloomington, IL",$107 - $142,Completed master’s or other advanced degree in...,18d,0,0,1,$,107.0000,142.0000,124.5000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,Data Scientist Consultant,American Technology Consulting,"Indianapolis, IN",$69 - $110,The Data Scientist Intermediate may have super...,4d,0,1,0,$,69.0000,110.0000,89.5000
92,Data Scientist,Eli Lilly and Company,"Indianapolis, IN",$66 - $165,"You will apply data science, machine learning,...",25d,0,0,1,$,66.0000,165.0000,115.5000
93,Data Scientist,Authenticx,"Indianapolis, IN",$77 - $125,"S. or further education in Mathematics, Econom...",3d,0,1,0,$,77.0000,125.0000,101.0000
94,Data Scientist,Novisync,"Indianapolis, IN",$41.48,The Data Scientist Intermediate may have super...,24h,1,0,1,$,86.2784,86.2784,86.2784
95,Lead GenAI Engineer,Deloitte,"Indianapolis, IN",$113 - $232,"A bachelor's degree in computer science, softw...",30d,0,0,1,$,113.0000,232.0000,172.5000

In [1495]:
df.describe()
##? after we handled the hourly salaries, we can see that min salary is 3K which isn't possible, i think it's monthly salary that i converted to annual salary by multiplying it by 12
##? same thing as max_salary, there is 2k

,Hourly,Glassdoor_Estimate,Employer_Provided,min_salary,max_salary,avg_salary
count,632.000000,632.000000,632.000000,544.000000,544.000000,544.000000
mean,0.015823,0.424051,0.436709,94.096094,143.180126,118.638110
std,0.124888,0.494589,0.496371,43.747181,76.712885,58.064505
min,0.000000,0.000000,0.000000,24.000000,25.000000,25.000000
25%,0.000000,0.000000,0.000000,65.000000,91.327600,80.500000
50%,0.000000,0.000000,0.000000,87.680000,130.000000,110.000000
75%,0.000000,1.000000,1.000000,118.000000,180.000000,150.000000
max,1.000000,1.000000,1.000000,380.000000,630.000000,445.000000

### job descreption section

In [1499]:
df['Job Description'].head(50)

0     Takes research methodology and translates the ...
1     3+ years of machine learning/statistical model...
2     Working closely with stakeholders, you'll asse...
3     You will work on our Science team and partner ...
4     Completed master’s or other advanced degree in...
5     Design, wireframe, and develop dashboards and ...
6     Mentoring and technical leadership capabilitie...
7     Experience with prompt engineering and few-sho...
8     Data Visualization and Reporting: Using tools ...
9     3+ years in decision analytics, data science, ...
10    Manage the execution of data science strategie...
11    Associates who live and work from Home in the ...
12    Strong documentation skills, including the abi...
13    Advanced degree in a quantitative field such a...
14    Work with evaluation/experimentation engineeri...
15    Work with evaluation/experimentation engineeri...
16    Bachelor’s degree in statistics, mathematics, ...
17    The role may include working on affordability ...
18    Advanced degree (Master’s) in Sociology, Econo...
19    Take accountability and ownership of end-to-en...
20    Hands-on expertise with fraud detection tools ...
21    This position will play a critical role in dat...
22    Hands on experience with Machine Learning and ...
23    Excellent overall communication skills, especi...
24    Quick to learn new systems, tools, and technic...
25    Bachelor’s degree in relevant field required. ...
26    Conduct research and analysis to improve the l...
27    2+ years of data science experience and Bachel...
28    Our main tasks include metrics defining, root ...
29    Experience in data science roles, preferably w...
30    Exposure to working with clients and customers...
31    Strong experience building and deploying machi...
32    Collaborate with data scientists, product mana...
33    Reporting directly into the CTO, this Lead Dat...
34    The ideal applicant holds a PhD (or equivalent...
35    Willingness to take ownership of analytics pro...
36    3–5+ years of experience in applied data scien...
37    Work closely with strategy and planning, insig...
38    This role would suit a candidate with machine ...
39    Industry experience in sectors such as retail,...
40    Experience building models for internal or bus...
41    Our autonomous model creates a huge opportunit...
42    Develop automation to scale yourself, leveragi...
43    No matter what you do, you’ll always be genero...
44    3 - 5 years’ of experience manipulating data s...
45    Work with product and engineering to improve o...
46    Experience (2-5 years) working as an associate...
47    Over 2 years data science experience ideally w...
48    We have offices in Coventry, Newcastle and Lon...
49    You will take ownership of our existing order ...
Name: Job Description, dtype: str